- name: Deploy Dockerized AI app
  hosts: app_servers
  become: yes
  vars:
    openai_api_key: "AIzaSyBaxidtgfq85EIjdMBI-ANKAiOrBqCtQDk"
    mlflow_uri: "http://13.49.238.45:5000"

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Copy app repo
      git:
        repo: 'https://github.com/sikaner/projects.git'
        dest: /home/ubuntu/app
        version: main

    - name: Create .env file
      template:
        src: ".env.j2"
        dest: "/home/ubuntu/app/.env"

    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: /home/ubuntu/app
        name: app_image
        tag: latest

    - name: Run Docker container
      community.docker.docker_container:
        name: app_container
        image: app_image:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        env_file: /home/ubuntu/app/.env

