---
- name: Deploy Dockerized AI app
  hosts: app_servers
  become: yes
  gather_facts: yes
  vars:
    openai_api_key: "AIzaSyBaxidtgfq85EIjdMBI-ANKAiOrBqCtQDk"
    mlflow_uri: "http://13.49.238.45:5000"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker repository
      shell: |
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" | sudo tee /etc/apt/sources.list.d/docker.list
      args:
        warn: false

    - name: Update apt after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE and containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone app repo
      git:
        repo: 'https://github.com/sikaner/projects.git'
        dest: /home/ubuntu/app
        version: main
        force: yes
        update: yes

    - name: Create .env file from template
      template:
        src: ".env.j2"
        dest: "/home/ubuntu/app/.env"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Install Ansible community.docker collection
      ansible.builtin.command: ansible-galaxy collection install community.docker
      args:
        creates: /home/ubuntu/.ansible/collections/ansible_collections/community/docker

    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: /home/ubuntu/app
        name: app_image
        tag: latest

    - name: Run Docker container
      community.docker.docker_container:
        name: app_container
        image: app_image:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        env_file: /home/ubuntu/app/.env
