---


pre_tasks:
- name: Ensure required apt packages are present
ansible.builtin.apt:
name:
- python3-pip
- git
update_cache: yes


roles:
- role: geerlingguy.docker # installed via ansible-galaxy


tasks:
- name: Ensure Docker Python SDK is installed
ansible.builtin.pip:
name: docker


- name: Create application directory
ansible.builtin.file:
path: "{{ app_dir }}"
state: directory
mode: "0755"


- name: Copy project source to target
ansible.builtin.copy:
src: ".." # from ansible/ directory, copy the parent (the app root)
dest: "{{ app_dir }}"
owner: root
group: root
mode: "0644"


- name: Render .env from template
ansible.builtin.template:
src: templates/.env.j2
dest: "{{ app_dir }}/.env"
mode: "0600"


- name: Build Docker image
community.docker.docker_image:
name: "{{ image_name }}"
build:
path: "{{ app_dir }}"
source: build


- name: Run (or restart) container
community.docker.docker_container:
name: "{{ app_name }}"
image: "{{ image_name }}"
state: started
restart_policy: unless-stopped
env_file: "{{ app_dir }}/.env"
published_ports:
- "{{ app_port | default('8000') }}:8000"
